name: Force Refresh Match
on: workflow_dispatch

jobs:
  refresh:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install correct Bundler version
        run: gem install bundler:2.7.2
      - name: Install dependencies
        run: bundle _2.7.2_ install
      - name: Run match force
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: bundle _2.7.2_ exec fastlane refresh_watch_match
