name: Force Refresh Match
on: workflow_dispatch

jobs:
  refresh:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install correct Bundler version
        run: gem install bundler:2.7.2
      - name: Install dependencies
        run: bundle _2.7.2_ install
      - name: Run match force
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.FASTLANE_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          TEAMID: ${{ secrets.TEAMID }}
        run: |
          encoded=$(echo -n "nini5182:$GH_PAT" | base64)

          cat > /tmp/api_key.json << EOF
          {
            "key_id": "$APP_STORE_CONNECT_API_KEY_KEY_ID",
            "issuer_id": "$APP_STORE_CONNECT_API_KEY_ISSUER_ID",
            "key": "$APP_STORE_CONNECT_API_KEY_KEY",
            "in_house": false
          }
          EOF

          bundle _2.7.2_ exec fastlane run match \
            type:appstore \
            app_identifier:"ru.artpancreas.7HWULNV59K.FreeAPS.watchkitapp" \
            git_basic_authorization:"$encoded" \
            readonly:false \
            force:true \
            api_key_path:"/tmp/api_key.json"
